site_name: Wiki CréaNum
site_author: Les Bibliothèques UdeM
site_url: https://bibudem.github.io/wiki/
site_description: Documentation et projets en création numérique

# Github

repo_name: bibudem/wiki
repo_url: https://github.com/bibudem/wiki

theme:
  language: fr
  name: material
  custom_dir: overrides
  font:
    text: Open Sans
    code: JetBrains Mono
    font: false
  logo: assets/logo/logo-web.webp
  favicon: assets/logo/favicon.ico
  icon:
    edit: material/pencil 
    view: material/eye
    repo: fontawesome/brands/github
  
  palette: 
    # light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Passer en mode sombre
    # dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Passer en mode clair
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
#   - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.path
    - navigation.indexes  
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - announce.dismiss
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.code.annotate
    - content.tooltips
    - content.tabs.link

# Paramètres de markdown extensions, pour en savoir plus : https://facelessuser.github.io/pymdown-extensions/

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.keys
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      base_path:
      - docs/logiciels
      - .
      auto_append: 
      - includes/abbreviations.md
      check_paths: true

# Paramètres de la table des matières

  - toc:
      permalink: true
      permalink_title: Lien permanent vers cette section
      toc_depth: 2
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/tablesort.js

extra_css:
  - assets/stylesheets/styleudem.css
  
# Analytics

extra:
  generator: false
  analytics: 
    provider: google
    property: G-45S4QV2SKS
    feedback:
      title: L'information sur cette page vous a-t-elle été utile? 
      ratings:
        - icon: material/emoticon-happy-outline
          name: Cette page a été utile
          data: 1
          note: >-
            Merci pour votre rétroaction!
        - icon: material/emoticon-sad-outline
          name: Cette page pourrait être améliorée
          data: 0
          note: >- 
            Merci pour votre rétroaction! Aidez-nous à améliorer la page en utilisant ce
            <a href="..." target="_blank" rel="noopener">formulaire</a>.

# Réseaux sociaux

  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/wikicn
      name: CréaNum sur Github

    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/bibudem
      name: Les Bibliothèques UdeM sur Twitter

    - icon: fontawesome/brands/facebook
      link: https://facebook.com/bibudem
      name: Les Bibliothèques UdeM sur Facebook

    - icon: fontawesome/solid/paper-plane
      link: mailto:<creanum@bib.umontreal.ca>
      name: Courriel


# Navigation

nav:
  - Accueil: index.md
  - Documentation: 
    - documentation/index.md
    - Impression 3D: 
      - Introduction:
        - Guide de l'impression 3D: impression3d/introduction.md
        - Trouver des modèles: impression3d/modeles.md
        - Logiciels de modélisation : impression3d/logiciels.md
        - Réparer la première couche d'un modèle: impression3d/reparer.md
        - Créer un modèle 3D à partir d'une image: impression3d/creer-modele-image.md
        - FAQ: impression3d/faq.md
      - Prusa i3 Mk3s+: impression3d/prusa.md
      - Ultimaker 2/S3: impression3d/ultimaker.md
      - Zortrax Inkspire: impression3d/zortrax.md
    - Électroniques:
      - Arduino: electronique/arduino.md
      - Raspberry Pi: electronique/raspberrypi.md
      - Internet des Objets:
        - Arduino IDE pour l'ESP8266: electronique/iot/arduino.md
        - Connecter un ESP à Blynk: electronique/iot/blynk.md
        - Les modes de veille du ESP 8266: electronique/iot/veille.md
    - Réalité virtuelle:
      - Mise en garde: vr/mises-en-garde.md
      - Casque Oculus GO:
        - Guide d'utilisation: vr/oculus-go.md
        - Catalogue d'expériences immersives: vr/catalogue.md
        - FAQ: vr/faq.md
    - Production Audio/Vidéo:
      - Audio: 
        - Guide Baladodiffusion: production-audio-video/guide-balado.md
        - RodeCaster Pro : production-audio-video/rodecasterpro.md  
      - Vidéo:
        - Guide de l'enregisrement vidéo: production-audio-video/guide-video.md
        - OBS : production-audio-video/obs.md
      - Édition:
        - ffmpeg : production-audio-video/ffmpeg.md
        - Adobe Premiere Pro : production-audio-video/premierepro.md
        - Audacity : production-audio-video/audacity.md
        - Adobe Audition : production-audio-video/audacity.md
  - Projets: 
    - projets/index.md
  - Logiciels: logiciels/index.md
  - Équipements: equipements/index.md
  - Communauté: 
    - communaute/index.md
    - Guide des bonnes pratiques : communaute/guide-contribution.md
    - Formations offertes : communaute/formations.md
  - À propos:
    - Objectifs et philosophie: a-propos/objectifs.md
    - L'équipe CréaNum: a-propos/equipe.md
    - Nous joindre: a-propos/nous-joindre.md
    - En savoir plus:
      - Accessibilité : a-propos/accessibilite.md
      - Condition d'utilisation : [https://bib.umontreal.ca/conditions-bibliotheques]
      - Confidentialité : [https://secretariatgeneral.umontreal.ca/protection-et-acces-a-linformation/complement-dinformation-sur-la-confidentialite/]