site_name: Wiki CréaNum
site_author: Les Bibliothèques UdeM
site_url: https://bibudem.github.io/creanum/
site_description: Documentation et projets en création numérique

# Github
repo_name: bibudem/creanum
repo_url: https://github.com/bibudem/creanum
edit_uri: edit/main/docs/

theme:
  language: fr
  name: material
  custom_dir: overrides
  font:
    text: Open Sans
    code: JetBrains Mono
    font: false
  logo: assets/logo/logo-web.webp
  favicon: assets/logo/favicon.ico
  icon:
    edit: material/pencil 
    view: material/eye
    repo: fontawesome/brands/github
    admonition:
      abstract: material/mouse

  
  palette: 
    # mode clair
    - scheme: default

      toggle:
        icon: material/eye
        name: Passer en mode sombre
    # mode sombre
    - scheme: slate
      accent: yellow
      toggle:
        icon: material/eye-outline
        name: Passer en mode clair
  
  features:
#    - navigation.instant
    - navigation.tracking
    - navigation.tabs
#   - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.path
    - navigation.indexes  
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    # - announce.dismiss
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.code.annotate
    - content.tooltips
    - content.tabs.link

# Paramètres de markdown extensions, pour en savoir plus : https://facelessuser.github.io/pymdown-extensions/

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.keys
  - footnotes
  - pymdownx.progressbar
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      base_path:
      - docs/logiciels
      - .
      auto_append: 
      - includes/abbreviations.md
      check_paths: true

# Paramètres de la table des matières

  - toc:
      permalink: true
      permalink_title: Permalien vers cette section
      toc_depth: 2
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/tablesort.js

extra_css:
  - assets/stylesheets/styleudem.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css


  
# Analytics

extra:
  generator: false
  analytics: 
    provider: google
    property: G-45S4QV2SKS
    feedback:
      title: L'information sur cette page vous a-t-elle été utile? 
      ratings:
        - icon: material/emoticon-happy-outline
          name: Cette page a été utile
          data: 1
          note: >-
            Merci pour votre rétroaction!
        - icon: material/emoticon-sad-outline
          name: Cette page pourrait être améliorée
          data: 0
          note: >- 
            Merci pour votre rétroaction! Aidez-nous à améliorer la page en utilisant ce
            <a href="..." target="_blank" rel="noopener">formulaire</a>.

# Réseaux sociaux

  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/bibudem/creanum
      name: CréaNum sur Github

    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/bibudem
      name: Les Bibliothèques UdeM sur Twitter

    - icon: fontawesome/brands/facebook
      link: https://facebook.com/bibudem
      name: Les Bibliothèques UdeM sur Facebook

    - icon: fontawesome/solid/paper-plane
      link: mailto:<creanum@bib.umontreal.ca>
      name: Courriel