AnneJulie:
  name: Anne-Julie Tremblay
  description: Technicienne en documentation
  avatar: https://gravatar.com/avatar/e935421afa194776e2c4199a990b8275?s=200&d=retro&r=x

Indiana:
  name: Indiana Delsart
  description: Bibliothécaire
  avatar: https://gravatar.com/avatar/e935421afa194776e2c4199a990b8275?s=200&d=retro&r=x

Jérémy:
  name: Jérémy Prime
  description: Technicien en documentation
  avatar: https://gravatar.com/avatar/e935421afa194776e2c4199a990b8275?s=200&d=retro&r=x

Emir:
  name: Emir Chouchane
  description: Conseiller en médiation technologique
  avatar: https://gravatar.com/avatar/e935421afa194776e2c4199a990b8275?s=200&d=retro&r=x

Maude:
  name: Maude Auberson-Lavoie
  description: Stagiaire médiation technologique
  avatar: https://gravatar.com/avatar/e935421afa194776e2c4199a990b8275?s=200&d=retro&r=x
