name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          
      - name: Set up build cache
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-${{ hashFiles('.cache/**') }}
          path: .cache

      - run: pip install -r requirements.txt
      - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

      - name: Conversion des images en WebP et remplacement des extensions
        run: python webp.py

      - run: mkdocs gh-deploy --config-file mkdocs.insiders.yml --force
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
